source(here::here('R/01-fetch-data.R'))
source(here::here('R/02-spatial-plot.R'))
source(here::here('R/03-ggplotly-plot.R'))
source(here::here('R/04-polygon-plot.R'))
source(here::here('R/05-country-plot.R'))
source(here::here('R/06-leaflet-plot.R'))
source(here::here('R/07-datatable.R'))
# source(here::here('R/10-analyze-data.R'))